using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MC_Login
{
    public partial class SplashScreen : Form
    {
        public SplashScreen()
        {
            InitializeComponent();
        }

        private void pictureBox1_Click(object sender, EventArgs e)
        {
            
        }

        private void SplashScreen_Load(object sender, EventArgs e)
        {
            timer1.Start();
        }

        private void timer1_Tick(object sender, EventArgs e)
        {
            Label sure = new Label();
            sure.Text = "238";
            sure.Text = "237";
            sure.Text = "236";
            sure.Text = "235";
            sure.Text = "234";
            sure.Text = "233";
            sure.Text = "232";
            sure.Text = "231";
            sure.Text = "230";
            sure.Text = "229";
            sure.Text = "228";
            sure.Text = "227";
            sure.Text = "226";
            sure.Text = "225";
            sure.Text = "224";
            sure.Text = "223";
            sure.Text = "222";
            sure.Text = "221";
            sure.Text = "220";
            sure.Text = "219";
            sure.Text = "218";
            sure.Text = "217";
            sure.Text = "216";
            sure.Text = "215";
            sure.Text = "214";
            sure.Text = "213";
            sure.Text = "212";
            sure.Text = "211";
            sure.Text = "210";
            sure.Text = "209";
            sure.Text = "208";
            sure.Text = "207";
            sure.Text = "206";
            sure.Text = "205";
            sure.Text = "204";
            sure.Text = "203";
            sure.Text = "202";
            sure.Text = "201";
            sure.Text = "200";
            sure.Text = "199";
            sure.Text = "198";
            sure.Text = "197";
            sure.Text = "196";
            sure.Text = "195";
            sure.Text = "194";
            sure.Text = "193";
            sure.Text = "192";
            sure.Text = "191";
            sure.Text = "190";
            sure.Text = "189";
            sure.Text = "188";
            sure.Text = "187";
            sure.Text = "186";
            sure.Text = "185";
            sure.Text = "184";
            sure.Text = "183";
            sure.Text = "182";
            sure.Text = "181";
            sure.Text = "180";
            sure.Text = "179";
            sure.Text = "178";
            sure.Text = "177";
            sure.Text = "176";
            sure.Text = "175";
            sure.Text = "174";
            sure.Text = "173";
            sure.Text = "172";
            sure.Text = "171";
            sure.Text = "170";
            sure.Text = "169";
            sure.Text = "168";
            sure.Text = "167";
            sure.Text = "166";
            sure.Text = "165";
            sure.Text = "164";
            sure.Text = "163";
            sure.Text = "162";
            sure.Text = "161";
            sure.Text = "160";
            sure.Text = "159";
            sure.Text = "158";
            sure.Text = "157";
            sure.Text = "156";
            sure.Text = "155";
            sure.Text = "154";
            sure.Text = "153";
            sure.Text = "152";
            sure.Text = "151";
            sure.Text = "150";
            sure.Text = "159";
            sure.Text = "158";
            sure.Text = "157";
            sure.Text = "156";
            sure.Text = "155";
            sure.Text = "154";
            sure.Text = "153";
            sure.Text = "152";
            sure.Text = "151";
            sure.Text = "150";
            sure.Text = "149";
            sure.Text = "148";
            sure.Text = "147";
            sure.Text = "146";
            sure.Text = "145";
            sure.Text = "144";
            sure.Text = "143";
            sure.Text = "142";
            sure.Text = "141";
            sure.Text = "140";
            sure.Text = "139";
            sure.Text = "138";
            sure.Text = "137";
            sure.Text = "136";
            sure.Text = "135";
            sure.Text = "134";
            sure.Text = "133";
            sure.Text = "132";
            sure.Text = "131";
            sure.Text = "130";
            sure.Text = "129";
            sure.Text = "128";
            sure.Text = "127";
            sure.Text = "126";
            sure.Text = "125";
            sure.Text = "124";
            sure.Text = "123";
            sure.Text = "122";
            sure.Text = "121";
            sure.Text = "120";
            sure.Text = "119";
            sure.Text = "118";
            sure.Text = "117";
            sure.Text = "116";
            sure.Text = "115";
            sure.Text = "114";
            sure.Text = "113";
            sure.Text = "112";
            sure.Text = "111";
            sure.Text = "110";
            sure.Text = "109";
            sure.Text = "108";
            sure.Text = "107";
            sure.Text = "106";
            sure.Text = "105";
            sure.Text = "104";
            sure.Text = "103";
            sure.Text = "102";
            sure.Text = "101";
            sure.Text = "100";
            sure.Text = "99";
            sure.Text = "98";
            sure.Text = "97";
            sure.Text = "96";
            sure.Text = "95";
            sure.Text = "94";
            sure.Text = "93";
            sure.Text = "92";
            sure.Text = "91";
            sure.Text = "90";
            sure.Text = "89";
            sure.Text = "88";
            sure.Text = "87";
            sure.Text = "86";
            sure.Text = "85";
            sure.Text = "84";
            sure.Text = "83";
            sure.Text = "82";
            sure.Text = "81";
            sure.Text = "80";
            sure.Text = "79";
            sure.Text = "78";
            sure.Text = "77";
            sure.Text = "76";
            sure.Text = "75";
            sure.Text = "74";
            sure.Text = "73";
            sure.Text = "72";
            sure.Text = "71";
            sure.Text = "70";
            sure.Text = "69";
            sure.Text = "68";
            sure.Text = "67";
            sure.Text = "66";
            sure.Text = "65";
            sure.Text = "64";
            sure.Text = "63";
            sure.Text = "62";
            sure.Text = "61";
            sure.Text = "60";
            sure.Text = "59";
            sure.Text = "58";
            sure.Text = "57";
            sure.Text = "56";
            sure.Text = "55";
            sure.Text = "54";
            sure.Text = "53";
            sure.Text = "52";
            sure.Text = "51";
            sure.Text = "50";
            sure.Text = "49";
            sure.Text = "48";
            sure.Text = "47";
            sure.Text = "46";
            sure.Text = "45";
            sure.Text = "44";
            sure.Text = "43";
            sure.Text = "42";
            sure.Text = "41";
            sure.Text = "40";
            sure.Text = "39";
            sure.Text = "38";
            sure.Text = "37";
            sure.Text = "36";
            sure.Text = "35";
            sure.Text = "34";
            sure.Text = "33";
            sure.Text = "32";
            sure.Text = "31";
            sure.Text = "30";
            sure.Text = "29";
            sure.Text = "28";
            sure.Text = "27";
            sure.Text = "26";
            sure.Text = "25";
            sure.Text = "24";
            sure.Text = "23";
            sure.Text = "22";
            sure.Text = "21";
            sure.Text = "20";
            sure.Text = "19";
            sure.Text = "18";
            sure.Text = "17";
            sure.Text = "16";
            sure.Text = "15";
            sure.Text = "14";
            sure.Text = "13";
            sure.Text = "12";
            sure.Text = "11";
            sure.Text = "10";
            sure.Text = "9";
            sure.Text = "8";
            sure.Text = "7";
            sure.Text = "6";
            sure.Text = "5";
            sure.Text = "4";
            sure.Text = "3";
            sure.Text = "2";
            sure.Text = "1";
            sure.Text = "0";
            this.Hide();
            Form1 frm = new Form1();
            frm.Show();
            timer1.Stop();
        }
    }
}
